import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h3>CSR: Pokemon</h3>
        <h3>SSR: Berry</h3>
        <h3>SSG fallback true: Item</h3>
        <h3>SSG fallback false: Location</h3>
        <h3>ISR: Move</h3>
      </main>
    </>
  )
}
